version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "23:00"
    timezone: America/Chicago
  open-pull-requests-limit: 99
  allow:
  - dependency-type: all

# Check for updates to GitHub Actions every week
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
