version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "23:00"
    timezone: America/Chicago
  open-pull-requests-limit: 99
  ignore:
    # All nucore-umass dependencies updates are handled
    # in nucore-open. Whenever this changes we should
    # allow only a specifc subset gem to be updated here.
    - dependency-name: '*'
  allow:
  - dependency-type: all
  groups:
    rails-gems:
      update-types:
        - patch
        - minor

      patterns:
        - rails
        - railties
        - actioncable
        - actionmailbox
        - actionmailer
        - actionpack
        - actiontext
        - actionview
        - activejob
        - activemodel
        - activerecord
        - activestorage

# Check for updates to GitHub Actions every week
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
