version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "23:00"
    timezone: America/Chicago
  open-pull-requests-limit: 99
  ignore:
    # All nucore-umass dependencies updates are handled
    # in nucore-open. Whenever this changes we should
    # allow only a specifc subset gem to be updated here.
    - dependency-name: '*'
