version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
    exclude_patterns:
      - "vendor/assets"
      - "vendor/engines/**/vendor/assets"
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    exclude_patterns:
      - "**.gemspec"
      - "spec/**"
      - "vendor/engines/**/spec/**"
      - "vendor/engines/*/lib/*/engine.rb"
      - "vendor/engines/*/*.gemspec"
      - "vendor/assets/**"
    config:
      languages:
      - ruby
      - javascript
  rubocop:
    enabled: true
    channel: rubocop-0-58
    config:
      file: ".rubocop.yml"
exclude_patterns:
- bin/
- config/
- db/
- script/
- "vendor/engines/fine_uploader"
