engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
    config: .coffeelint.json
  duplication:
    enabled: true
    exclude_paths:
      - "**.gemspec"
      - "spec/**"
      - "vendor/engines/**/spec/**"
      - "vendor/engines/*/lib/*/engine.rb"
      - "vendor/engines/*/*.gemspec"
    config:
      languages:
      - ruby
      - javascript
  rubocop:
    enabled: true
ratings:
  paths:
  - "app/**"
  - "lib/**"
  - "spec/**"
  - "vendor/engines/**"
  - Gemfile.lock
exclude_paths:
- bin/
- config/
- db/
- script/
