AllCops:
  TargetRubyVersion: 2.1

inherit_from:
  - .rubocop-txi.yml
  - .rubocop_todo.yml

# Overrides can go here, but try to conform to TXI standards as specified in
# .rubocop-txi.yml when possible.
#
# Example...
# Metrics/CyclomaticComplexity:
#   Enabled: false # We've got nasty methods!
#
