# To start all docker containers run: `docker-compose up`
#
version: '3'
services:
  app:
    build: .
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - gem_cache:/gems
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - LDAP_HOST=ldap
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    logging:
      driver: none
  # ldap:
  #   image: osixia/openldap
  #   command: "--copy-service"
  #   volumes:
  #     - "ldap-data:/var/lib/ldap"
  #     # Loads some default users into the database
  #     - "./vendor/engines/ldap_authentication/spec/fixtures:/container/service/slapd/assets/config/bootstrap/ldif/custom"
  # ldap-admin:
  #   image: osixia/phpldapadmin
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - ldap
  #   environment:
  #     - PHPLDAPADMIN_LDAP_HOSTS=ldap
  #     - PHPLDAPADMIN_HTTPS=false

volumes:
  db-data:
    driver: local
  ldap-data:
    driver: local
  gem_cache: {}
