# To start all docker containers run: `docker-compose up`
#
version: '3.8'
services:
  app:
    build:
      context: .
      # To debug Github Actions CI issues:
      # 1) Replace `target: develop` with `dockerfile: Dockerfile.github-actions`,
      # 2) Update the `command:` (for example `command: bash -c "cd app && bundle install && bundle exec rake teaspoon"`)
      # 3) Run `docker compose build app`.
      # 4) Re-run as needed ot attach to the container to run other debugging commands
      target: develop
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - db
      - selenium
    volumes:
      - .:/app
      - gem_cache:/gems
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - SMTP_HOST=mailcatcher
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_APP_PORT=3000
      - DOCKER_LOCAL_DEV=true
      # Uncomment below to run teaspoon tests
      # - RAILS_ENV=test
      # - TEASPOON_RAILS_ENV=test
    tty: true
    stdin_open: true
  delayed_job:
    build:
      context: .
      target: develop
    command: bundle exec rake jobs:work
    depends_on:
      - app
    volumes:
      - .:/app
      - gem_cache:/gems
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - SMTP_HOST=mailcatcher
    stdin_open: true
    tty: true
  db:
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    tty: true
    stdin_open: true
    logging:
      driver: none
  mailcatcher:
    build:
      context: .
      target: develop
    command: bash -c "gem install mailcatcher && mailcatcher --ip 0.0.0.0 --no-quit -f"
    ports:
      - "1080:1080"
    volumes:
      - .:/app
      - gem_cache:/gems
    tty: true
    stdin_open: true
  # For system-tests and teaspoon
  selenium:
    image: selenium/standalone-chrome:119.0.6045.199-chromedriver-119.0.6045.105
    logging:
      driver: none
    ports:
      - "5900:5900"
volumes:
  db-data:
    driver: local
  gem_cache: {}
