---
- name: ensure nginx is at the latest version
  yum:
    name: nginx
    state: latest
  notify:
    - Start nginx

- firewalld:
    service: https
    permanent: yes
    state: enabled
- firewalld:
    service: http
    permanent: yes
    state: enabled
