- name: Install required python package for managing selinux
  yum:
    name: policycoreutils-python
    state: latest
  become: yes

- name: Ensure selinux doesn't block the nginx->app connection
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  become: yes
