---
- name: Start nginx
  systemd:
      name: nginx
      state: started
  become: yes
- name: Reload nginx
  systemd:
      name: nginx
      state: reloaded
  become: yes
- name: Enable nginx
  systemd:
      name: nginx
      state: enabled
