---
- name: Start nginx
  systemd:
      name: nginx
      state: started
  become: yes
- name: Reload nginx
  systemd:
      name: nginx
      state: reloaded
  become: yes
- name: Enable nginx
  systemd:
      name: nginx
      enabled: true
  become: yes
- name: Restart firewalld
  systemd:
      name: firewalld
      state: reloaded
  become: yes
