name: "Setup test env"
description: "Install dependencies and create the database"

runs:
  using: "composite"
  steps:
    # Install dependencies for mysql2 gem
    - run: apt-get update && apt-get -y install libmysqlclient-dev
      shell: bash
    - name: cache gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-bundle-

    - run: bundle install --path vendor/bundle
      shell: bash
    - run: cp config/database.yml.mysql.template config/database.yml
      shell: bash
    - run: cp config/secrets.yml.template config/secrets.yml
      shell: bash
    - run: bundle exec rake db:create db:schema:load
      shell: bash

