name: Setup dependencies
description: Install Ruby/JS dependencies and write test configuration

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-node
    - uses: ./.github/actions/setup-bundler
    - run: cp config/database.yml.mysql.template config/database.yml
      shell: bash
    - run: cp config/secrets.yml.template config/secrets.yml
      shell: bash
