defaults: &defaults
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE", "9d8d4819b39557e45f0363d0cc30d9290b4472af72c151e6733a9dec98a158f7029a8734b0c3cb4d205004648988280d3633606d9b10714916107f3f6a3c26d7") %>
  rollbar: <%= ENV["ROLLBAR_ACCESS_TOKEN"] %>
  run_recurring_tasks: false

  # You should change this if you want to be able to access the API
  api:
    basic_auth_name: <%= ENV.fetch("NUCORE_API_USERNAME", "nucore") %>
    basic_auth_password: <%= ENV.fetch("NUCORE_API_PASSWORD", SecureRandom.hex) %>

  # You should change this if you want to be able to access the SecureRooms API
  secure_rooms_api:
    basic_auth_name: <%= ENV.fetch("SECURE_ROOMS_USERNAME", "secure_rooms_api") %>
    basic_auth_password: <%= ENV.fetch("SECURE_ROOMS_PASSWORD", SecureRandom.hex) %>

  # Uncomment below to use the ScishieldAdapter class
  # SCISHIELD_RSA_PRIVATE_KEY must return a single-line string with "\n" characters.
  # Otherwise the YAML parser will escape newlines as whitespace characters (" ").
  # scishield:
    # key: <%= ENV.fetch("SCISHIELD_KEY", "") %>
    # key_id: <%= ENV.fetch("SCISHIELD_KEY_ID", "") %>
    # rsa_private_key: '<%= ENV.fetch("SCISHIELD_RSA_PRIVATE_KEY", "") %>'
    # scishield_endpoint: <%= ENV.fetch("SCISHIELD_ENDPOINT", "") %>

  # To use S3, add your credentials here and enable S3 in your environment (see doc/migrating_to_s3.md)
  # paperclip:
  #   aws_access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY", "Your-Key-Here") %>
  #   aws_secret_access_key: <ENV.fetch("AWS_SECRET_ACCESS_KEY", "Your-Key-Here") %>

  # To use ActiveStorage, add your credentials here and enable Azure or AWS in your environment file: config.active_storage.service = :s3
  active_storage:
    s3:
      access_key_id: <%= ENV.fetch("BUCKETEER_AWS_ACCESS_KEY_ID", "123abc") %>
      secret_access_key: <%= ENV.fetch("BUCKETEER_AWS_SECRET_ACCESS_KEY", "123abc") %>
      bucket: <%= ENV.fetch("BUCKETEER_BUCKET_NAME", "123abc") %>

development:
  <<: *defaults
  # Run `bundle exec rake secret` to generate a value for this
  secret_key_base: ~

test:
  <<: *defaults
  secret_key_base: value_needed_for_ci
  scishield:
    scishield_endpoint: "https://test-university.scishield.com/jsonapi/raft_training_record/raft_training_record"

stage:
  <<: *defaults

production:
  <<: *defaults
