header_logo_path: ~
email_logo_path: ~
display_app_name_in_header: true
footer_logo_link: "https://www.umass.edu/ials/core-facilities"
stage_color: <%= ENV.fetch("STAGE_COLOR", nil) %>

price_group:
  name:
    base: "Base Rate"
    external: "External Rate"
    cancer_center: "IALS Members"

time_zone: "Eastern Time (US & Canada)"

accounts:
  # Most frequently used account by UMass
  product_default: 753080
  revenue_account_default: 699900

admin_holds:
  repeat_end_date_in_weeks: <%= ENV.fetch("ADMIN_HOLD_REPEAT_END_DATE_IN_WEEKS", 12) %>

financial:
  # in the format MM-DD
  fiscal_year_begins: 07-01
  journal_format:
    # Note that xml and xls have custom responders so they don't need a class_name
    # - key: xml
    # - key: xls
    - key: csv
      class_name: UmassCorum::Journals::JournalCsv
      mime_type: csv
    - key: prn
      class_name: UmassCorum::Journals::JournalPrn
      mime_type: text # This is optional if it matches the key
  default_journal_cutoff_time: "16:45"

converters:
  product_to_journal_rows: UmassCorum::Journals::ProductToJournalRowAttributes
  order_detail_to_journal_rows: UmassCorum::Journals::OrderDetailToJournalRowAttributes

research_safety_adapter:
  class_name: <%= ENV.fetch("RESEARCH_SAFETY_ADAPTER_CLASS", "ResearchSafetyAdapters::ResearchSafetyAlwaysCertifiedAdapter") %>
  scishield:
    batch_sleep_time: <%= ENV.fetch("SCISHIELD_BATCH_SLEEP_TIME", 20) %>
    batch_size: <%= ENV.fetch("SCISHIELD_BATCH_SIZE", 15) %>
    retry_max: <%= ENV.fetch("SCISHIELD_SYNC_RETRY_MAX", 5) %>
    iat_offset: <%= ENV.fetch("SCISHIELD_IAT_OFFSET", 0) %>

statement_pdf:
  class_name: UmassCorum::StatementPdf
  font_name: Roboto

validator:
  class_name: UmassCorum::SpeedTypeValidator
  test:
    factory: # relative to Rails.root
    helper: 'spec/validator_helper' # relative to Rails.root

testing:
  account_class_name: UmassCorum::SpeedTypeAccount
  account_factory: speed_type_account
  api_account_factory: api_speed_type

email:
  from: "corum@umass.edu"
  invoice_bcc: ~
  fake:
    enabled: false

# support_email_subject is only applied on the Support header link
# this will be encoded by the mail_to helper, so use standard spaces (not %20)
support_email: corum@umass.edu
support_email_subject: "CORUM Support Request"

nonbillable_user:
  email: "nonbillableuser@example.come"
  username: "none (nonbillable)"

order_details:
  list_transformer: SplitAccounts::OrderDetailListTransformer

# Make sure to update order_row_importers/headers keys in override/en.yml
order_import_template_name: umass_corum_bulk_import_template.csv

reservations:
  grace_period: <%= 5.minutes %>
  timeout_period: <%= 12.hours %>

occupancies:
  timeout_period: <%= 12.hours %>

billing:
  review_period: <%= 14.days %>

relays:
  test:
    admin_enabled: false
    reservation_enabled: false
  development:
    admin_enabled: false
    reservation_enabled: false
  staging:
    admin_enabled: true
    reservation_enabled: true
  production:
    admin_enabled: true
    reservation_enabled: true

#
# For these settings use SettingsHelper#feature_on?
feature:
  global_billing_administrator: true
  global_billing_administrator_users_tab: true
  create_users: true
  lookup_netids: false
  limit_short_description: true
  order_assignment_notifications: true
  password_update: true
  expense_accounts: true
  edit_accounts: true
  suspend_accounts: true
  product_specific_contacts: true
  training_requests: true
  daily_view: true
  split_accounts: true
  print_order_detail: false
  user_based_price_groups: true
  my_files: true
  # results file notifications requires that my_files be on as well
  results_file_notifications: true
  set_statement_search_start_date: false
  send_statement_emails: true
  ready_for_journal_notice: true
  journals_may_span_fiscal_years: false
  equipment_list: true
  price_change_reason_required: true
  can_manage_global_price_groups: true
  cross_facility_reports: true
  product_list_columns: false
  azlist: false
  use_manage: false
  facility_banner_notice: true
  charge_full_price_on_cancellation: true
  price_policy_requires_note: true
  multi_facility_accounts: true
  facility_directors_can_manage_price_groups: true
  account_reference_field: false
  facility_payment_urls: true
  uses_ldap_authentication: false
  kiosk_view: true
  bypass_kiosk_auth: true
  revenue_account_editable: false
  active_storage: false
  active_storage_for_images_only: true
  facility_tile_list: <%= ENV.fetch("FACILITY_TILE_LIST", false) %>
  facility_tile_list_admin: true
  po_require_affiliate_account: true
  walkup_reservations: true
  show_reconciliation_deposit_number: <%= ENV.fetch("RECONCILIATION_DEPOSIT_NUMBER", false) %>
  show_daily_rate_option: true
  sanger_enabled_service: <%= ENV.fetch("SANGER_ENABLED_SERVICE", false) %>
  well_plate_alternative_csv_format: <%= ENV.fetch("well_plate_alternative_csv_format", false) %>
  disable_relay_synaccess_rev_a: false
  allow_global_billing_admin_update_actual_prices: true
  export_order_disputes: false
  show_estimates_option: <%= !Rails.env.production? %>

split_accounts:
  # Roles are allowed to create Split Accounts
  create_roles:
    - administrator
    # - account_manager

# To use S3 or another Paperclip backend, you can override the configuration in the
# appropriate environment, e.g. config/settings/production.yml.
# If you wish to use it for development, add it to a `config/settings/development.local.yml`
# file (this file is gitignored).
# This needs to be here even if you're using Active Storage
paperclip:
  storage: filesystem
  url: ":rails_relative_url_root/uploads/:class/:attachment/:id_partition/:style/:safe_filename"
  path: ":rails_root/public/uploads/:class/:attachment/:id_partition/:style/:safe_filename"

saml:
  create_user: true
  login_enabled: true
  # We've been seeing certificate expiration errors, so we're temporarily using a
  # locally stored version of the metadata.
  # You can add allowance for clock drift between the sp and idp - this is a time in seconds.
  allowed_clock_drift_in_seconds: 1
  idp_metadata: https://webauth.umass.edu/saml2/idp/metadata.php
  # Overridden in staging/production
  # certificate_file: saml-certificate.p12 # Do not check in to version control.
  driver:
    name_identifier_format: urn:oasis:names:tc:SAML:2.0:nameid-format:transient
    idp_slo_target_url: https://webauth.umass.edu/saml2/idp/SingleLogoutService.php
  metadata_parse_options: # Optional, but setting the sso_binding option is highly recommended. See RubySaml::IdpMetadataParser for valid options.
    sso_binding: ["urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"] #  Otherwise the binding will default to the first one specified in the IdP by default, which can cause problems if the IdP metadata changes.
  attribute_map:
    # There is a nicer "FriendlyName" attribute in the SAML response, but the ruby-saml gem
    # only reads the "Name" attribute, which we receive as these weird urn:oids.
    # FriendlyName="eduPersonPrincipalName"
    "urn:oid:1.3.6.1.4.1.5923.1.1.1.6": email
    # FriendlyName="uid"
    "urn:oid:0.9.2342.19200300.100.1.1": username
    # FriendlyName="givenName"
    "urn:oid:2.5.4.42": first_name
    # FriendlyName="sn" (surname)
    "urn:oid:2.5.4.4": last_name
    # FriendlyName="cardId"
    "https://federation.campuslabs.com/attributes/cardId": umass_emplid
  user_updating:
    skip_attributes: email

price_policy_note_options: ~
order_detail_price_change_reason_options: ~

google_analytics_key: ~

devise:
  lock_strategy: :failed_attempts
  unlock_strategy: :email
  minutes_to_unlock_in: 5
