header_logo_path: ~
display_app_name_in_header: true

price_group:
  name:
    base: 'Base Rate'
    external: 'External Rate'

time_zone: "Eastern Time (US & Canada)"

accounts:
  # Most frequently used account by UMass
  product_default: 753080
  revenue_account_default: 699900

financial:
  # in the format MM-DD
  fiscal_year_begins: 07-01
  journal_format:
    # Note that xml and xls have custom responders
    # - key: xml
    # - key: xls
    - key: csv
      class_name: UmassCorum::Journals::JournalCsv
      mime_type: csv
    - key: prn
      class_name: UmassCorum::Journals::JournalPrn
      mime_type: text # This is optional if it matches the key
  default_journal_cutoff_time: "16:45"

converters:
  product_to_journal_rows: UmassCorum::Journals::ProductToJournalRowAttributes
  order_detail_to_journal_rows: UmassCorum::Journals::OrderDetailToJournalRowAttributes

statement_pdf:
  class_name: UmassCorum::StatementPdf
  font_name: Roboto

validator:
  class_name: UmassCorum::SpeedTypeValidator
  test:
    factory: # relative to Rails.root
    helper: 'spec/validator_helper' # relative to Rails.root

email:
  from: "corum@umass.edu"
  fake:
    enabled: false

support_email: ~

order_details:
  list_transformer: SplitAccounts::OrderDetailListTransformer

reservations:
  grace_period: <%= 5.minutes %>
  timeout_period: <%= 12.hours %>

occupancies:
  timeout_period: <%= 12.hours %>

billing:
  review_period: <%= 14.days %>

relays:
  test:
    admin_enabled: false
    reservation_enabled: false
  development:
    admin_enabled: false
    reservation_enabled: false
  staging:
    admin_enabled: true
    reservation_enabled: true
  production:
    admin_enabled: true
    reservation_enabled: true

#
# For these settings use SettingsHelper#feature_on?
feature:
  global_billing_administrator: true
  global_billing_administrator_users_tab: true
  create_users: true
  lookup_netids: false
  limit_short_description: true
  order_assignment_notifications: true
  password_update: true
  expense_accounts: true
  edit_accounts: true
  suspend_accounts: true
  product_specific_contacts: true
  training_requests: true
  daily_view: true
  split_accounts: true
  print_order_detail: false
  user_based_price_groups: true
  my_files: true
  # results file notifications requires that my_files be on as well
  results_file_notifications: true
  set_statement_search_start_date: false
  send_statement_emails: true
  ready_for_journal_notice: true
  journals_may_span_fiscal_years: false
  equipment_list: true
  price_change_reason_required: true
  can_manage_global_price_groups: true
  cross_facility_reports: false
  product_list_columns: false
  azlist: false
  use_manage: false
  facility_banner_notice: true
  charge_full_price_on_cancellation: true
  price_policy_requires_note: true
  multi_facility_accounts: true
  facility_directors_can_manage_price_groups: true
  account_reference_field: false
  facility_payment_urls: true
  uses_ldap_authentication: false
  kiosk_view: true
  bypass_kiosk_auth: true
  revenue_account_editable: false

split_accounts:
  # Roles are allowed to create Split Accounts
  create_roles:
    - administrator
    # - account_manager

# To use S3 or another Paperclip backend, you can override the configuration in the
# appropriate environment, e.g. config/settings/production.yml.
# If you wish to use it for development, add it to a `config/settings/development.local.yml`
# file (this file is gitignored).
paperclip:
  storage: filesystem
  url: ":rails_relative_url_root/uploads/:class/:attachment/:id_partition/:style/:safe_filename"
  path: ":rails_root/public/uploads/:class/:attachment/:id_partition/:style/:safe_filename"

saml:
  create_user: false
  login_enabled: true
  # We've been seeing certificate expiration errors, so we're temporarily using a
  # locally stored version of the metadata.
  idp_metadata: "https://webauth.umass.edu/idp/shibboleth"
  # Overridden in staging/production
  # certificate_file: saml-certificate.p12 # Do not check in to version control.
  driver:
    name_identifier_format: urn:oasis:names:tc:SAML:2.0:nameid-format:transient
    idp_slo_target_url: https://webauth.umass.edu/Logout
  metadata_parse_options: # Optional, but setting the sso_binding option is highly recommended. See RubySaml::IdpMetadataParser for valid options.
    sso_binding: ["urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"] #  Otherwise the binding will default to the first one specified in the IdP by default, which can cause problems if the IdP metadata changes.
  attribute_map:
    # There is a nicer "FriendlyName" attribute in the SAML response, but the ruby-saml gem
    # only reads the "Name" attribute, which we receive as these weird urn:oids.
    # FriendlyName="eduPersonPrincipalName"
    "urn:oid:1.3.6.1.4.1.5923.1.1.1.6": email
    # FriendlyName="uid"
    "urn:oid:0.9.2342.19200300.100.1.1": username
    # FriendlyName="givenName"
    "urn:oid:2.5.4.42": first_name
    # FriendlyName="sn" (surname)
    "urn:oid:2.5.4.4": last_name
    # FriendlyName="cardId"
    "https://federation.campuslabs.com/attributes/cardId": umass_emplid
  user_updating:
    skip_attributes: email

price_policy_note_options: ~
order_detail_price_change_reason_options: ~

google_analytics_key: ~

devise:
  lock_strategy: :failed_attempts
