# use this file for school-specific settings overrides
#
# For these settings use SettingsHelper#feature_on?
feature:
  allow_global_billing_admin_update_actual_prices: true
  export_order_disputes: true
  billing_log_events: true
  show_account_opencontract_field: true
  hide_account_far_future_expiration: true
  show_account_price_groups_tab: true
