email:
  from: "nucore-noreply@nucore.stage.tablexi.com"
  fake:
    enabled: true
    to: ["mak@tablexi.com", "jason@tablexi.com", "john.newfry@tablexi.com"]
    whitelist: []
saml:
  certificate_file: config/saml-certificate.p12
