email:
  from: "nucore-noreply@nucore.stage.tablexi.com"
  fake:
    enabled: true
    to: ["jason@tablexi.com", "meara@tablexi.com"]
    whitelist: []

# paperclip:
#   storage: fog
#   fog_credentials:
#     provider: AWS
#     aws_access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY", Rails.application.secrets.dig(:paperclip, :aws_access_key_id)) %>
#     aws_secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY", Rails.application.secrets.dig(:paperclip, :aws_secret_access_key)) %>
#   fog_directory: "nucore-staging"
#   fog_public: false
#   path: ":class/:attachment/:id_partition/:style/:safe_filename"
