email:
  from: "nucore-noreply@nucore.stage.tablexi.com"
  fake:
    enabled: true
    to: ["mak@tablexi.com", "jason@tablexi.com", "john.newfry@tablexi.com"]
    whitelist: ["avinard@umass.edu", "andrew.scott@umass.edu", "stephen.battisti@umass.edu", "stevens@umass.edu"]
