email:
  from: "nucore-noreply@nucore.stage.tablexi.com"
  fake:
    enabled: true
    to: ["jason@tablexi.com", "meara@tablexi.com"]
    whitelist: []

# paperclip:
#   storage: fog
#   fog_credentials:
#     provider: AWS
#     aws_access_key_id: <%= Rails.application.secrets.dig(:paperclip, :aws_access_key_id) %>
#     aws_secret_access_key: <%= Rails.application.secrets.dig(:paperclip, :aws_secret_access_key) %>
#   fog_directory: "nucore-staging"
#   fog_public: false
