devise:
  secret_key: override-me-in-settings.local.yml

# These credentials are set randomly in the standard settings, but need to be
# more stable in a testing environment
secure_rooms_api:
  basic_auth_name: 51f5953d88c4c397eaf9bc11439887bf
  basic_auth_password: 4a2100348322d5c3c0bf52979450f7de
