---
- hosts: all
  tasks:
    - name: Add root authorized keys
      authorized_key:
        user: root
        state: present
        key: '{{ item }}'
      with_file:
        - public_keys/jhanggi.pub
    - name: Set up nucore authorized keys
      authorized_key:
        user: nucore
        state: present
        key: '{{ item }}'
      with_file:
        - public_keys/jhanggi.pub
