---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      yum:
        name: nginx
        state: latest
    - name: start nginx
      systemd:
          name: nginx
          state: started
    - firewalld:
        service: https
        permanent: yes
        state: enabled
    - firewalld:
        service: http
        permanent: yes
        state: enabled
