Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  # Centos does not have an official 7.7 vagrant box, only 7.6 and 7.8
  config.vm.box = "bento/centos-7.7"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end

  # These libraries here are installed by default on regular installations, just
  # not the cloud-base.
  config.vm.provision "shell", inline: "yum -y install epel-release python3-pip firewalld gpg cronie"

  config.vm.network "forwarded_port", guest: 80, host: 8888

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/hashicorp/vagrant/issues/5005
  config.ssh.insert_key = false

  config.vm.define "corum_machine1"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "site.yml"
    ansible.extra_vars = {
      "nginx_apps" => [
        {
          "host" => "nucore.stage.tablexi.com",
          "alias" => "localhost:8888 localhost",
          "user" => "corum",
          "rails_env" => "staging",
          "ruby_versions" => ["3.3.0"],
          "ssl" => false,
        }
      ]
    }
  end
end
