Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  config.vm.box = "fedora/29-cloud-base"

  # These libraries here are installed by default on regular installations, just
  # not the cloud-base.
  config.vm.provision "shell", inline: "yum -y install python3-pip firewalld gpg"

  config.vm.network "forwarded_port", guest: 80, host: 8888

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/hashicorp/vagrant/issues/5005
  config.ssh.insert_key = false

  config.vm.define "corum_machine1"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "site.yml"
    ansible.extra_vars = {
      "nginx_apps" => [
        {
          "host" => "nucore.stage.tablexi.com",
          "alias" => "localhost:8888 localhost",
          "user" => "nucore",
          "rails_env" => "staging",
        }
      ]
    }
  end
end
